/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baitu_jnitest_CalculatorHelper */

#ifndef _Included_com_baitu_jnitest_CalculatorHelper
#define _Included_com_baitu_jnitest_CalculatorHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baitu_jnitest_CalculatorHelper
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_baitu_jnitest_CalculatorHelper_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_baitu_jnitest_CalculatorHelper
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_baitu_jnitest_CalculatorHelper_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
